#pragma once
#include"../shellcode/cmdcode.h"
#include"../shellcode/filecode.h"
#include"../shellcode/infocode.h"
#include"../shellcode/maikefeng.h"
#include"../shellcode/regcode.h"
#include"../shellcode/servercode.h"
#include"../shellcode/shipin.h"
#include"../shellcode/systemcode.h"
#include"../shellcode/taskcode.h"
#include"../shellcode/yangshengqi.h"
#include"../shellcode/pingmu.h"
#include"../shellcode/keycode.h"
#include"../shellcode/houtai.h"
#include"../shellcode/toolscode.h"
#include"../shellcode/oldpingmu.h"
#include"../shellcode/updata.h"